/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jewellery;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jewellery.DBConnect.connect;

/**
 *
 * @author shrey
 */
public class CashUserDetails extends javax.swing.JFrame {

    /**
     * Creates new form CashUserDetails
     */
    public CashUserDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usercontact = new javax.swing.JTextField();
        userAdhar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        userPaqn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        useraddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(57, 68, 76));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Name:");

        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Contact:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Aadhar Number:");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("PAN Number:");

        usercontact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usercontactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usercontactFocusLost(evt);
            }
        });
        usercontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usercontactKeyReleased(evt);
            }
        });

        userAdhar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userAdharFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userAdharFocusLost(evt);
            }
        });
        userAdhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userAdharKeyReleased(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(238, 188, 81));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("USER DETAILS");

        savebtn.setBackground(new java.awt.Color(0, 153, 0));
        savebtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        savebtn.setText("Submit");
        savebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebtnMouseClicked(evt);
            }
        });
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        savebtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                savebtnKeyPressed(evt);
            }
        });

        userPaqn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userPaqnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userPaqnFocusLost(evt);
            }
        });
        userPaqn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userPaqnKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Address:");

        useraddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                useraddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                useraddressFocusLost(evt);
            }
        });
        useraddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                useraddressKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userPaqn, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(userAdhar)
                    .addComponent(usercontact)
                    .addComponent(username)
                    .addComponent(useraddress))
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usercontact, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAdhar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPaqn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useraddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public  void fillUserData(int bill) throws FileNotFoundException{
        String statement = "INSERT INTO cashpurchasedetails ( name, address, adhar_no, pan_no, contact_no, bill_no) VALUES ( '"+username.getText()+"', '"+useraddress.getText()+"', '"+userAdhar.getText()+"', '"+userPaqn.getText()+"', '"+usercontact.getText()+"', '"+String.valueOf(bill)+"');";
           Connection con = connect();
    try {
        Statement stmt = con.createStatement();
        System.out.println(statement);
        stmt.executeUpdate(statement);
    } catch (SQLException ex) {
        Logger.getLogger(CashUserDetails.class.getName()).log(Level.SEVERE, null, ex);
    }        
    }
    public void updateUserData(int bill) throws FileNotFoundException{
     String statement = "UPDATE `cashpurchasedetails` SET `name` = '"+username.getText()+"', `address` = '"+useraddress.getText()+"', `adhar_no` = '"+usercontact.getText()+"', `pan_no` = '"+userPaqn.getText()+"', `contact_no` = '"+usercontact.getText()+"' WHERE `bill_no` = "+String.valueOf(bill)+";";
           Connection con = connect();
    try {
        Statement stmt = con.createStatement();
       int result= stmt.executeUpdate(statement);
       if(result==1){
           JOptionPane.showMessageDialog(this, "User Added To Cash");
       }else{
           JOptionPane.showMessageDialog(this, "Error in saving User Please Add Accurate Data!!!");
    }
    } catch (SQLException ex) {
        Logger.getLogger(ExChange.class.getName()).log(Level.SEVERE, null, ex);
    }  
        
    }
    public void clear(){
        username.setText("");
        usercontact.setText("");
        userAdhar.setText("");
        userPaqn.setText("");
        useraddress.setText("");
    }
    public  void fetchData(int bill) throws FileNotFoundException{
        String statement = "SELECT * FROM `cashpurchasedetails` WHERE bill_no = "+String.valueOf(bill)+";";
           Connection con = connect();
           String id=null,name=null,contact=null,aadhar=null,pan=null,address=null;
    try {
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(statement);
        while(rs.next()){
                  id = rs.getString("id");
                  name = rs.getString("name");
                  aadhar = rs.getString("adhar_no");
                  pan = rs.getString("pan_no");
                  address = rs.getString("address");
                  contact = rs.getString("contact_no");      
        }

    } catch (SQLException ex) {
        Logger.getLogger(ExChange.class.getName()).log(Level.SEVERE, "Failed", ex);
    }
    username.setText(name);
    usercontact.setText(contact);
    userAdhar.setText(aadhar);
    userPaqn.setText(pan);
    this.useraddress.setText(address);
    }
    int pass = 0;
    int b = 0;
    public void setPass(int p,int bi){
         this.pass = p;
         this.b = bi;
    }
    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
         
//             if(pass == 1){
//               this.updateUserData(b);
//             }
                 
        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
            if (evt.getKeyCode() == KeyEvent.VK_ENTER){
             usercontact.requestFocus(); 
        }     // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyReleased

    private void usercontactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usercontactKeyReleased
            if (evt.getKeyCode() == KeyEvent.VK_ENTER){
             userAdhar.requestFocus(); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_usercontactKeyReleased

    private void userAdharKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userAdharKeyReleased
            if (evt.getKeyCode() == KeyEvent.VK_ENTER){
             userPaqn.requestFocus(); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_userAdharKeyReleased

    private void userPaqnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userPaqnKeyReleased
            if (evt.getKeyCode() == KeyEvent.VK_ENTER){
             useraddress.requestFocus(); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_userPaqnKeyReleased

    private void useraddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useraddressKeyPressed
        // TODO add your handling code here:
            if (evt.getKeyCode() == KeyEvent.VK_ENTER){
             savebtn.requestFocus(); 
        }
    }//GEN-LAST:event_useraddressKeyPressed

    private void savebtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_savebtnKeyPressed
        // TODO add your handling code here:
           if (evt.getKeyCode() == KeyEvent.VK_ENTER){
               this.setVisible(false);
             if(pass == 0){
                 try {
                     this.fillUserData(b);
                 } catch (FileNotFoundException ex) {
                     Logger.getLogger(CashUserDetails.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
             if(pass == 1){
                 try {
                     this.updateUserData(b);
                 } catch (FileNotFoundException ex) {
                     Logger.getLogger(CashUserDetails.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
        }
    }//GEN-LAST:event_savebtnKeyPressed

    private void savebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseClicked
    this.setVisible(false);
             if(pass == 0){
                 try {
                     this.fillUserData(b);
                 } catch (FileNotFoundException ex) {
                     Logger.getLogger(CashUserDetails.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
             if(pass == 1){
                 try {
                     this.updateUserData(b);
                 } catch (FileNotFoundException ex) {
                     Logger.getLogger(CashUserDetails.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnMouseClicked

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        username.setBackground(new Color(245, 230, 66));
        
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        username.setBackground(Color.white);
    }//GEN-LAST:event_usernameFocusLost

    private void usercontactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usercontactFocusGained
        usercontact.setBackground(new Color(245, 230, 66));
    }//GEN-LAST:event_usercontactFocusGained

    private void usercontactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usercontactFocusLost
        usercontact.setBackground(Color.white);
    }//GEN-LAST:event_usercontactFocusLost

    private void userAdharFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userAdharFocusGained
        userAdhar.setBackground(new Color(245, 230, 66));
    }//GEN-LAST:event_userAdharFocusGained

    private void userAdharFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userAdharFocusLost
        userAdhar.setBackground(Color.white);
    }//GEN-LAST:event_userAdharFocusLost

    private void userPaqnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPaqnFocusGained
        userPaqn.setBackground(new Color(245, 230, 66));
    }//GEN-LAST:event_userPaqnFocusGained

    private void userPaqnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPaqnFocusLost
        userPaqn.setBackground(Color.white);
    }//GEN-LAST:event_userPaqnFocusLost

    private void useraddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_useraddressFocusGained
        useraddress.setBackground(new Color(245, 230, 66));
    }//GEN-LAST:event_useraddressFocusGained

    private void useraddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_useraddressFocusLost
        useraddress.setBackground(Color.white);
    }//GEN-LAST:event_useraddressFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashUserDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField userAdhar;
    private javax.swing.JTextField userPaqn;
    private javax.swing.JTextField useraddress;
    private javax.swing.JTextField usercontact;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
