/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jewellery;

import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.jdesktop.swingx.JXImageView;
import jewellery.LoanBook;

/**
 *
 * @author 91888
 */
public class viewItems extends javax.swing.JFrame {

    /**
     * Creates new form viewItems
     */
    private int imageNumber = 0;

    public viewItems() {
        initComponents();
        loadImages();
        overrideDefaultCloseOperation();
    }
    private void overrideDefaultCloseOperation() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                dispose();
            }
        });
    }
    private void loadImages() {
        // Create a panel to hold the images
        JPanel imagePanel = new JPanel();
        LoanBook lb = new LoanBook();

        String[] imagePaths = {
            "C:/Users/91888/Pictures/Default.jpg",
        };
        try {
         
    JOptionPane.showMessageDialog(this, "Coming Path is...  "+lb.GetSelectedPartyName());
        Path destinationPath = Paths.get("assets/" + "Party1" + "/itemsImages/", "ITEM_PHOTO" + imageNumber + ".png");
        JOptionPane.showMessageDialog(this, "Path is  "+destinationPath);
        imagePaths[0] = destinationPath.toString();
    
        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error loading image in string : " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // Use GridLayout with 0 rows (means flexible) and 3 columns
        imagePanel.setLayout(new GridLayout(0, 3, 5, 5)); // 3 columns, 5px gap

        // Example: Load some images (replace with your actual image paths)
        for (String path : imagePaths) {
            try {
                // Load the image
                BufferedImage img = ImageIO.read(new File(path));

                // Create JXImageView component
                JXImageView imageView = new JXImageView();
                imageView.setImage(img);
                imageView.setPreferredSize(new java.awt.Dimension(200, 200));

                // Store the path in the component for later retrieval
                imageView.putClientProperty("imagePath", path);

                // Add mouse click listener
                imageView.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        showImagePopup(evt);
                    }
                });

                // Add to the panel
                imagePanel.add(imageView);
            } catch (IOException ex) {
                System.err.println("Couldn't load image: " + path);
                ex.printStackTrace();
            }
        }
        // Set the panel as the viewport view of the scroll pane
        jScrollPane1.setViewportView(imagePanel);
    }

    private void showImagePopup(java.awt.event.MouseEvent evt) {
        JXImageView source = (JXImageView) evt.getSource();
        String imagePath = (String) source.getClientProperty("imagePath");

        try {
            // Create popup dialog
            JDialog popup = new JDialog(this, "Image View", true);
            popup.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

            // Load the image in original size
            BufferedImage img = ImageIO.read(new File(imagePath));
            JXImageView largeImageView = new JXImageView();
            largeImageView.setImage(img);
            // largeImageView.setScaleToFit(true);

            // Add to scroll pane in case image is very large
            JScrollPane scrollPane = new JScrollPane(largeImageView);
            popup.add(scrollPane);

            // Set dialog size
            popup.setSize(800, 600);
            popup.setLocationRelativeTo(this);
            popup.setVisible(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error loading image: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
